/*

ALGG 14-01-2017 Definición de clase PlanificacionDiaria.

*/

export class PlanificacionDiaria {
  constructor(
    public id: number,
    public nombre_completo: string,
    public contrato_id: number,
    public titulo:string,
    public tarea_id: number,
    public persona_id: number,
    public nombre: string,
    public ape1: string,
    public ape2: string,
    public dni: string,
    public tlfno1: string,
    public mes: number,
    public anno: number,
    public puesto_id: number,
    public puesto_cod: string,
    public puesto_desc: string,
    public fecha_inicio: string,
    public ciclo_master_id: number,
    public fecha_fin: string,
    public total_dias: number,
    public semana: number,
    public dia1: number,
    public dia2: number,
    public dia3: number,
    public dia4: number,
    public dia5: number,
    public dia6: number,
    public dia7: number,
    public dia8: number,
    public dia9: number,
    public dia10: number,
    public dia11: number,
    public dia12: number,
    public dia13: number,
    public dia14: number,
    public dia15: number,
    public dia16: number,
    public dia17: number,
    public dia18: number,
    public dia19: number,
    public dia20: number,
    public dia21: number,
    public dia22: number,
    public dia23: number,
    public dia24: number,
    public dia25: number,
    public dia26: number,
    public dia27: number,
    public dia28: number,
    public dia29: number,
    public dia30: number,
    public dia31: number,
    public dia1_aus: string,
    public dia2_aus: string,
    public dia3_aus: string,
    public dia4_aus: string,
    public dia5_aus: string,
    public dia6_aus: string,
    public dia7_aus: string,
    public dia8_aus: string,
    public dia9_aus: string,
    public dia10_aus: string,
    public dia11_aus: string,
    public dia12_aus: string,
    public dia13_aus: string,
    public dia14_aus: string,
    public dia15_aus: string,
    public dia16_aus: string,
    public dia17_aus: string,
    public dia18_aus: string,
    public dia19_aus: string,
    public dia20_aus: string,
    public dia21_aus: string,
    public dia22_aus: string,
    public dia23_aus: string,
    public dia24_aus: string,
    public dia25_aus: string,
    public dia26_aus: string,
    public dia27_aus: string,
    public dia28_aus: string,
    public dia29_aus: string,
    public dia30_aus: string,
    public dia31_aus: string,
    public es_lunes_festivo: string,
    public es_martes_festivo: string,
    public es_miercoles_festivo: string,
    public es_jueves_festivo: string,
    public es_viernes_festivo: string,
    public es_sabado_festivo: string,
    public es_domingo_festivo: string,
    public turno_libre_id: number
  ) { }
}
